apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: invaleed/argocd-demo-1
  newTag: d42d9afa4fd8ec62b7f4967fcb78dc70a04462f5
resources:
- ../base
