apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: invaleed/argocd-demo
  newTag: 65a2feefc76a82b65137a30e2812c8b5824878cf
resources:
- ../base
