apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: invaleed/argocd-demo-1
  newTag: 72da91cb85c8237f496b621eedca6721725f91d2
resources:
- ../base
